server:
  port: 8080

spring:
  datasource:
#    username: homestead
#    password: secret
#    url: jdbc:mysql://192.168.58.10:3306/mybatis?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    url: jdbc:mysql://172.21.107.247:3306/mybatis?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
